import "./globals.css";

import { Inter } from "next/font/google";

import { Container, HStack, Stack } from "@chakra-ui/react";

import { Providers } from "./providers";

import type { Metadata } from "next";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main>
          <Providers>
            <Container maxW="container.lg" h="full">
              <Stack>{children}</Stack>
            </Container>
          </Providers>
        </main>
      </body>
    </html>
  );
}
