import "./globals.css";

import { map } from "lodash";
import { Inter } from "next/font/google";

import { Navbar } from "@/components/navbar";
import { Container, HStack, Stack } from "@chakra-ui/react";

import { fonts } from "./fonts";
import { Providers } from "./providers";

import type { Metadata } from "next";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={map(fonts, (e) => e["variable"]).join(" ")}>
      <body>
        <main>
          <Providers>
            <Navbar />
            <Container maxW="container.lg" h="full" mt={10}>
              <Stack>{children}</Stack>
            </Container>
          </Providers>
        </main>
      </body>
    </html>
  );
}
